import { head as Header } from "next/head";

const Head = () => {
  <Header>
    <title>Create Next App</title>
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='/favicon.ico' />
  </Header>;
};

export default Head;
